{% set name = "oceanumlab" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oceanumlab-{{ version }}.tar.gz
  sha256: 4668823d52d63b00b24da6036559926961ad3615dcc505f20f5f951f316e47a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >=3.10
    - tornado
    - jupyterlab >=4.0.0,<5

test:
  imports:
    - oceanumlab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oceanum.io
  summary: A Jupyterlab extension to interact with the Oceanum.io platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ondave
