{% set name = "oceanumlab" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oceanumlab-{{ version }}.tar.gz
  sha256: b95e4920dd2cbc822455a87e08a727497e7ef3900d42f836a8de00354f2c2747

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2
    - pip
  run:
    - python >={{ python_min }}
    - tornado
    - jupyterlab >=4.0.0,<5

test:
  imports:
    - oceanumlab
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://oceanum.io
  summary: A Jupyterlab extension to interact with the Oceanum.io platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ondave
